# Generated by Django 4.1.3 on 2022-12-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=15)),
                ('clean_or_dirty', models.BooleanField()),
                ('item_fits', models.BooleanField()),
                ('sibling_has_matching', models.BooleanField()),
                ('item_image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_description', models.CharField(max_length=50)),
                ('outfit_image', models.ImageField(upload_to=None)),
                ('bow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_bow', to='girlsclothesapi.clothingitem')),
                ('dress_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_dress', to='girlsclothesapi.clothingitem')),
                ('pant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_pant', to='girlsclothesapi.clothingitem')),
                ('shirt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_shirt', to='girlsclothesapi.clothingitem')),
                ('shoe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_shoe', to='girlsclothesapi.clothingitem')),
                ('sock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_sock', to='girlsclothesapi.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('dress_size', models.CharField(max_length=5)),
                ('shoe_size', models.CharField(max_length=5)),
                ('shirt_size', models.CharField(max_length=5)),
                ('pant_size', models.CharField(max_length=5)),
                ('underwear_or_diaper_size', models.CharField(max_length=5)),
                ('sock_size', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsBeingWorn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsclothesapi.clothingitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsclothesapi.outfit')),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='clothing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsclothesapi.clothingtype'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='clothing_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsclothesapi.clothinguse'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsclothesapi.kid'),
        ),
    ]
